# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_vehiculo', models.CharField(max_length=6)),
                ('documento_persona', models.CharField(max_length=15)),
                ('lugar', models.CharField(max_length=40)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.CharField(max_length=255)),
            ],
        ),
    ]
